
output_dir: './workdirs/colorchar128_dbg'
structure: 'linear'
dataset:
  img_dir: '../color_symbol_7k' 
  folder: False
  resolution: 128
sched:
  epochs: [60, 120, 120, 120, 240, 240]
  batch_sizes: [128, 128, 128, 64, 32, 16]
  fade_in_percentage: [50, 50, 50, 50, 50, 50, 50, 50, 50]
model:
  d_optim:
    beta_1: 0.0
    beta_2: 0.99
    eps: 1e-8
    learning_rate: 0.003
  g_optim:
    beta_1: 0.0
    beta_2: 0.99
    eps: 1e-8
    learning_rate: 0.003